### PR TITLE
Added oom killer score so print3d does not get killed

### PR DESCRIPTION
**Pull request by olijf**

### CODE REVIEW

**Comment by peteruithoven** [comment]
Just as you explained I find different oom killer score ranges, both -17 to -1000 for example. Could you add a link in the comment that refers to some docs? Sadly enough I didn't find any on the OpenWRT wiki.

**Comment by olijf** [comment]
well you have the legacy oom_score value that can range from -17 to +17 (before linux kernel ~< 2.4) and you have the oom_score_adj that is currently being used (although it seems both files exist in /proc/<pid>/)

see

**Comment by olijf** [comment]
allright:
oom_adj (what I previously called oom_score) can range from -16 to +15 with -17 being a special oom_disabled value.

oom_score_adj is more modern and can range from -1000 to +1000. It does not have a oom killer disabled but with -1000 (added to the badness score) there is a very very slim change that the oom killer can kill it
See http://zurlinux.com/?p=2147 
> The lowest possible value, -1000, is equivalent to disabling oom killing entirely for that task since it will always report a badness score of 0.

**Comment by peteruithoven** [comment]
Thanks!

**Pull request merged**
